"""add password_reset_token model

Revision ID: 24170b779211
Revises: e9cb6e251f81
Create Date: 2026-07-05 17:58:41.801272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24170b779211'
down_revision: Union[str, Sequence[str], None] = 'e9cb6e251f81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash'),
    sa.UniqueConstraint('user_id')
    )
    op.add_column('activation_tokens', sa.Column('token_hash', sa.String(length=64), nullable=False))
    op.drop_constraint(op.f('activation_tokens_token_key'), 'activation_tokens', type_='unique')
    op.create_unique_constraint(None, 'activation_tokens', ['token_hash'])
    op.drop_column('activation_tokens', 'token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activation_tokens', sa.Column('token', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'activation_tokens', type_='unique')
    op.create_unique_constraint(op.f('activation_tokens_token_key'), 'activation_tokens', ['token'], postgresql_nulls_not_distinct=False)
    op.drop_column('activation_tokens', 'token_hash')
    op.drop_table('password_reset_tokens')
    # ### end Alembic commands ###
